all:
	aarch64-linux-gnu-gcc -g -I./include print.c -o print.o
	aarch64-linux-gnu-gcc -g -I./include encrypt.c -o encrypt.o
	aarch64-linux-gnu-gcc -g -I./include decrypt.c -o decrypt.o

clean:
	rm *.o
