#ifndef __GREEN_TEE_SMC_H__
#define __GREEN_TEE_SMC_H__

#define GREEN_TEE_SMC_LINUX_INIT	128
#define GREEN_TEE_SMC_LINUX_PRINT	129
#define GREEN_TEE_SMC_LINUX_ENCRYPT 130
#define GREEN_TEE_SMC_LINUX_DECRYPT 131

#endif
